export const USER_PATTERNS = {
  CREATE: { cmd: 'create_user' },
  FIND_ALL: { cmd: 'find_all_users' },
  FIND_ONE: { cmd: 'find_user' },
  UPDATE: { cmd: 'update_user' },
  DELETE: { cmd: 'delete_user' },
  FIND_BY_EMAIL: { cmd: 'find_user_by_email' },
};

export const AUTH_PATTERNS = {
  LOGIN: { cmd: 'AUTH_LOGIN' },
  LOGOUT: { cmd: 'AUTH_LOGOUT' },
  REFRESH_TOKEN: { cmd: 'AUTH_REFRESH_TOKEN' },
  RESET_PASSWORD_SEND_EMAIL: { cmd: 'AUTH_RESET_PASSWORD_SEND_EMAIL' },
  RESET_PASSWORD_CONFIRM: { cmd: 'AUTH_RESET_PASSWORD_CONFIRM' },
};

export const ROLE_PATTERNS = {
  CREATE: { cmd: 'ROLES_CREATE' },
  UPDATE: { cmd: 'ROLES_UPDATE' },
  GET_BY_ID: { cmd: 'ROLES_GET_BY_ID' },
  LIST: { cmd: 'ROLES_LIST' },
  DELETE: { cmd: 'ROLES_DELETE' },
  ADD_PERMISSION: { cmd: 'ROLES_ADD_PERMISSION' },
  REMOVE_PERMISSION: { cmd: 'ROLES_REMOVE_PERMISSION' },
};

export const PERMISSION_PATTERNS = {
  CREATE: { cmd: 'PERMISSIONS_CREATE' },
  UPDATE: { cmd: 'PERMISSIONS_UPDATE' },
  GET_BY_ID: { cmd: 'PERMISSIONS_GET_BY_ID' },
  LIST: { cmd: 'PERMISSIONS_LIST' },
  DELETE: { cmd: 'PERMISSIONS_DELETE' },
};

export const ORDER_PATTERNS = {
  CREATE: { cmd: 'create_order' },
  FIND_ALL: { cmd: 'find_all_orders' },
  FIND_BY_USER: { cmd: 'find_orders_by_user' },
};

export const SITE_PATTERNS = {
  CREATE: { cmd: 'SITES_CREATE' },
  UPDATE: { cmd: 'SITES_UPDATE' },
  GET_BY_ID: { cmd: 'SITES_GET_BY_ID' },
  LIST: { cmd: 'SITES_LIST' },
  DELETE: { cmd: 'SITES_DELETE' },
  GET_TYPES: { cmd: 'SITES_GET_TYPES' },
};

export const SUPPLIER_PATTERNS = {
  CREATE: { cmd: 'SUPPLIERS_CREATE' },
  UPDATE: { cmd: 'SUPPLIERS_UPDATE' },
  GET_BY_ID: { cmd: 'SUPPLIERS_GET_BY_ID' },
  LIST: { cmd: 'SUPPLIERS_LIST' },
  DELETE: { cmd: 'SUPPLIERS_DELETE' },
};

export const RAW_MATERIAL_PATTERNS = {
  CREATE: { cmd: 'RAW_MATERIALS_CREATE' },
  UPDATE: { cmd: 'RAW_MATERIALS_UPDATE' },
  GET_BY_ID: { cmd: 'RAW_MATERIALS_GET_BY_ID' },
  GET_BY_SUPPLIER: { cmd: 'RAW_MATERIALS_GET_BY_SUPPLIER' },
  LIST: { cmd: 'RAW_MATERIALS_LIST' },
  DELETE: { cmd: 'RAW_MATERIALS_DELETE' },
};

export const PURCHASE_ORDER_PATTERNS = {
  CREATE: { cmd: 'PURCHASE_ORDERS_CREATE' },
  UPDATE: { cmd: 'PURCHASE_ORDERS_UPDATE' },
  GET_BY_ID: { cmd: 'PURCHASE_ORDERS_GET_BY_ID' },
  LIST: { cmd: 'PURCHASE_ORDERS_LIST' },
  DELETE: { cmd: 'PURCHASE_ORDERS_DELETE' },
  APPROVE: { cmd: 'PURCHASE_ORDERS_APPROVE' },
  CANCEL: { cmd: 'PURCHASE_ORDERS_CANCEL' },
};

export const GOODS_RECEIPT_PATTERNS = {
  CREATE: { cmd: 'GOODS_RECEIPTS_CREATE' },
  UPDATE: { cmd: 'GOODS_RECEIPTS_UPDATE' },
  GET_BY_ID: { cmd: 'GOODS_RECEIPTS_GET_BY_ID' },
  LIST: { cmd: 'GOODS_RECEIPTS_LIST' },
  DELETE: { cmd: 'GOODS_RECEIPTS_DELETE' },
};

export const QC_SAMPLE_PATTERNS = {
  CREATE: { cmd: 'QC_SAMPLES_CREATE' },
  UPDATE: { cmd: 'QC_SAMPLES_UPDATE' },
  GET_BY_ID: { cmd: 'QC_SAMPLES_GET_BY_ID' },
  LIST: { cmd: 'QC_SAMPLES_LIST' },
  DELETE: { cmd: 'QC_SAMPLES_DELETE' },
  ASSIGN_TESTS: { cmd: 'QC_SAMPLES_ASSIGN_TESTS' },
  RECEIVE_SAMPLE: { cmd: 'QC_SAMPLES_RECEIVE_SAMPLE' },
  GET_BY_GOODS_RECEIPT_ITEM: { cmd: 'QC_SAMPLES_GET_BY_GOODS_RECEIPT_ITEM' },
};

export const QC_TEST_PATTERNS = {
  CREATE: { cmd: 'QC_TESTS_CREATE' },
  UPDATE: { cmd: 'QC_TESTS_UPDATE' },
  GET_BY_ID: { cmd: 'QC_TESTS_GET_BY_ID' },
  LIST: { cmd: 'QC_TESTS_LIST' },
  DELETE: { cmd: 'QC_TESTS_DELETE' },
  GET_BY_MATERIAL: { cmd: 'QC_TESTS_GET_BY_MATERIAL' },
};

export const QC_RESULT_PATTERNS = {
  CREATE: { cmd: 'QC_RESULTS_CREATE' },
  UPDATE: { cmd: 'QC_RESULTS_UPDATE' },
  GET_BY_ID: { cmd: 'QC_RESULTS_GET_BY_ID' },
  LIST: { cmd: 'QC_RESULTS_LIST' },
  DELETE: { cmd: 'QC_RESULTS_DELETE' },
  GET_BY_SAMPLE: { cmd: 'QC_RESULTS_GET_BY_SAMPLE' },
  SUBMIT_TO_QA: { cmd: 'QC_RESULTS_SUBMIT_TO_QA' },
  COMPLETE_TESTING: { cmd: 'QC_RESULTS_COMPLETE_TESTING' },
};

export const QA_RELEASE_PATTERNS = {
  CREATE: { cmd: 'QA_RELEASES_CREATE' },
  UPDATE: { cmd: 'QA_RELEASES_UPDATE' },
  GET_BY_ID: { cmd: 'QA_RELEASES_GET_BY_ID' },
  LIST: { cmd: 'QA_RELEASES_LIST' },
  DELETE: { cmd: 'QA_RELEASES_DELETE' },
  GET_BY_SAMPLE: { cmd: 'QA_RELEASES_GET_BY_SAMPLE' },
  COMPLETE_CHECKLIST: { cmd: 'QA_RELEASES_COMPLETE_CHECKLIST' },
  MAKE_DECISION: { cmd: 'QA_RELEASES_MAKE_DECISION' },
  NOTIFY_WAREHOUSE: { cmd: 'QA_RELEASES_NOTIFY_WAREHOUSE' },
};