export const USER_PATTERNS = {
  CREATE: { cmd: 'create_user' },
  FIND_ALL: { cmd: 'find_all_users' },
  FIND_ONE: { cmd: 'find_user' },
  UPDATE: { cmd: 'update_user' },
  DELETE: { cmd: 'delete_user' },
  FIND_BY_EMAIL: { cmd: 'find_user_by_email' },
};

export const AUTH_PATTERNS = {
  LOGIN: { cmd: 'AUTH_LOGIN' },
  LOGOUT: { cmd: 'AUTH_LOGOUT' },
  REFRESH_TOKEN: { cmd: 'AUTH_REFRESH_TOKEN' },
  RESET_PASSWORD_SEND_EMAIL: { cmd: 'AUTH_RESET_PASSWORD_SEND_EMAIL' },
  RESET_PASSWORD_CONFIRM: { cmd: 'AUTH_RESET_PASSWORD_CONFIRM' },
};

export const ROLE_PATTERNS = {
  CREATE: { cmd: 'ROLES_CREATE' },
  UPDATE: { cmd: 'ROLES_UPDATE' },
  GET_BY_ID: { cmd: 'ROLES_GET_BY_ID' },
  LIST: { cmd: 'ROLES_LIST' },
  DELETE: { cmd: 'ROLES_DELETE' },
  ADD_PERMISSION: { cmd: 'ROLES_ADD_PERMISSION' },
  REMOVE_PERMISSION: { cmd: 'ROLES_REMOVE_PERMISSION' },
};

export const PERMISSION_PATTERNS = {
  CREATE: { cmd: 'PERMISSIONS_CREATE' },
  UPDATE: { cmd: 'PERMISSIONS_UPDATE' },
  GET_BY_ID: { cmd: 'PERMISSIONS_GET_BY_ID' },
  LIST: { cmd: 'PERMISSIONS_LIST' },
  DELETE: { cmd: 'PERMISSIONS_DELETE' },
};

export const ORDER_PATTERNS = {
  CREATE: { cmd: 'create_order' },
  FIND_ALL: { cmd: 'find_all_orders' },
  FIND_BY_USER: { cmd: 'find_orders_by_user' },
};

export const SITE_PATTERNS = {
  CREATE: { cmd: 'SITES_CREATE' },
  UPDATE: { cmd: 'SITES_UPDATE' },
  GET_BY_ID: { cmd: 'SITES_GET_BY_ID' },
  LIST: { cmd: 'SITES_LIST' },
  DELETE: { cmd: 'SITES_DELETE' },
  GET_TYPES: { cmd: 'SITES_GET_TYPES' },
};

export const SUPPLIER_PATTERNS = {
  CREATE: { cmd: 'SUPPLIERS_CREATE' },
  UPDATE: { cmd: 'SUPPLIERS_UPDATE' },
  GET_BY_ID: { cmd: 'SUPPLIERS_GET_BY_ID' },
  LIST: { cmd: 'SUPPLIERS_LIST' },
  DELETE: { cmd: 'SUPPLIERS_DELETE' },
};

export const RAW_MATERIAL_PATTERNS = {
  CREATE: { cmd: 'RAW_MATERIALS_CREATE' },
  UPDATE: { cmd: 'RAW_MATERIALS_UPDATE' },
  GET_BY_ID: { cmd: 'RAW_MATERIALS_GET_BY_ID' },
  GET_BY_SUPPLIER: { cmd: 'RAW_MATERIALS_GET_BY_SUPPLIER' },
  LIST: { cmd: 'RAW_MATERIALS_LIST' },
  DELETE: { cmd: 'RAW_MATERIALS_DELETE' },
};

export const PURCHASE_ORDER_PATTERNS = {
  CREATE: { cmd: 'PURCHASE_ORDERS_CREATE' },
  UPDATE: { cmd: 'PURCHASE_ORDERS_UPDATE' },
  GET_BY_ID: { cmd: 'PURCHASE_ORDERS_GET_BY_ID' },
  LIST: { cmd: 'PURCHASE_ORDERS_LIST' },
  DELETE: { cmd: 'PURCHASE_ORDERS_DELETE' },
  APPROVE: { cmd: 'PURCHASE_ORDERS_APPROVE' },
  CANCEL: { cmd: 'PURCHASE_ORDERS_CANCEL' },
};

export const GOODS_RECEIPT_PATTERNS = {
  CREATE: { cmd: 'GOODS_RECEIPTS_CREATE' },
  UPDATE: { cmd: 'GOODS_RECEIPTS_UPDATE' },
  GET_BY_ID: { cmd: 'GOODS_RECEIPTS_GET_BY_ID' },
  LIST: { cmd: 'GOODS_RECEIPTS_LIST' },
  DELETE: { cmd: 'GOODS_RECEIPTS_DELETE' },
};

export const QC_SAMPLE_PATTERNS = {
  CREATE: { cmd: 'QC_SAMPLES_CREATE' },
  UPDATE: { cmd: 'QC_SAMPLES_UPDATE' },
  GET_BY_ID: { cmd: 'QC_SAMPLES_GET_BY_ID' },
  LIST: { cmd: 'QC_SAMPLES_LIST' },
  DELETE: { cmd: 'QC_SAMPLES_DELETE' },
  ASSIGN_TESTS: { cmd: 'QC_SAMPLES_ASSIGN_TESTS' },
  RECEIVE_SAMPLE: { cmd: 'QC_SAMPLES_RECEIVE_SAMPLE' },
  GET_BY_GOODS_RECEIPT_ITEM: { cmd: 'QC_SAMPLES_GET_BY_GOODS_RECEIPT_ITEM' },
};

export const QC_TEST_PATTERNS = {
  CREATE: { cmd: 'QC_TESTS_CREATE' },
  UPDATE: { cmd: 'QC_TESTS_UPDATE' },
  GET_BY_ID: { cmd: 'QC_TESTS_GET_BY_ID' },
  LIST: { cmd: 'QC_TESTS_LIST' },
  DELETE: { cmd: 'QC_TESTS_DELETE' },
  GET_BY_MATERIAL: { cmd: 'QC_TESTS_GET_BY_MATERIAL' },
};

export const QC_RESULT_PATTERNS = {
  CREATE: { cmd: 'QC_RESULTS_CREATE' },
  UPDATE: { cmd: 'QC_RESULTS_UPDATE' },
  GET_BY_ID: { cmd: 'QC_RESULTS_GET_BY_ID' },
  LIST: { cmd: 'QC_RESULTS_LIST' },
  DELETE: { cmd: 'QC_RESULTS_DELETE' },
  GET_BY_SAMPLE: { cmd: 'QC_RESULTS_GET_BY_SAMPLE' },
  SUBMIT_TO_QA: { cmd: 'QC_RESULTS_SUBMIT_TO_QA' },
  COMPLETE_TESTING: { cmd: 'QC_RESULTS_COMPLETE_TESTING' },
};

export const QA_RELEASE_PATTERNS = {
  CREATE: { cmd: 'QA_RELEASES_CREATE' },
  UPDATE: { cmd: 'QA_RELEASES_UPDATE' },
  GET_BY_ID: { cmd: 'QA_RELEASES_GET_BY_ID' },
  LIST: { cmd: 'QA_RELEASES_LIST' },
  DELETE: { cmd: 'QA_RELEASES_DELETE' },
  GET_BY_SAMPLE: { cmd: 'QA_RELEASES_GET_BY_SAMPLE' },
  COMPLETE_CHECKLIST: { cmd: 'QA_RELEASES_COMPLETE_CHECKLIST' },
  MAKE_DECISION: { cmd: 'QA_RELEASES_MAKE_DECISION' },
  NOTIFY_WAREHOUSE: { cmd: 'QA_RELEASES_NOTIFY_WAREHOUSE' },
};

export const QA_DEVIATION_PATTERNS = {
  CREATE: { cmd: 'QA_DEVIATIONS_CREATE' },
  UPDATE: { cmd: 'QA_DEVIATIONS_UPDATE' },
  GET_BY_ID: { cmd: 'QA_DEVIATIONS_GET_BY_ID' },
  LIST: { cmd: 'QA_DEVIATIONS_LIST' },
  DELETE: { cmd: 'QA_DEVIATIONS_DELETE' },
  GET_BY_SOURCE: { cmd: 'QA_DEVIATIONS_GET_BY_SOURCE' },
  ASSIGN: { cmd: 'QA_DEVIATIONS_ASSIGN' },
  UPDATE_STATUS: { cmd: 'QA_DEVIATIONS_UPDATE_STATUS' },
};

export const WAREHOUSE_PATTERNS = {
  // Inventory
  INVENTORY_CREATE: { cmd: 'WAREHOUSE_INVENTORY_CREATE' },
  INVENTORY_UPDATE: { cmd: 'WAREHOUSE_INVENTORY_UPDATE' },
  INVENTORY_GET_BY_ID: { cmd: 'WAREHOUSE_INVENTORY_GET_BY_ID' },
  INVENTORY_LIST: { cmd: 'WAREHOUSE_INVENTORY_LIST' },
  INVENTORY_DELETE: { cmd: 'WAREHOUSE_INVENTORY_DELETE' },
  INVENTORY_GET_BY_MATERIAL: { cmd: 'WAREHOUSE_INVENTORY_GET_BY_MATERIAL' },
  INVENTORY_GET_BY_BATCH: { cmd: 'WAREHOUSE_INVENTORY_GET_BY_BATCH' },
  INVENTORY_VERIFY: { cmd: 'WAREHOUSE_INVENTORY_VERIFY' },
  
  // Stock Movements
  MOVEMENT_CREATE: { cmd: 'WAREHOUSE_MOVEMENT_CREATE' },
  MOVEMENT_GET_BY_ID: { cmd: 'WAREHOUSE_MOVEMENT_GET_BY_ID' },
  MOVEMENT_LIST: { cmd: 'WAREHOUSE_MOVEMENT_LIST' },
  MOVEMENT_GET_BY_REFERENCE: { cmd: 'WAREHOUSE_MOVEMENT_GET_BY_REFERENCE' },
  
  // Putaway
  PUTAWAY_CREATE: { cmd: 'WAREHOUSE_PUTAWAY_CREATE' },
  PUTAWAY_GET_BY_ID: { cmd: 'WAREHOUSE_PUTAWAY_GET_BY_ID' },
  PUTAWAY_LIST: { cmd: 'WAREHOUSE_PUTAWAY_LIST' },
  PUTAWAY_ASSIGN_LOCATION: { cmd: 'WAREHOUSE_PUTAWAY_ASSIGN_LOCATION' },
  PUTAWAY_COMPLETE: { cmd: 'WAREHOUSE_PUTAWAY_COMPLETE' },
  PUTAWAY_GET_BY_QA_RELEASE: { cmd: 'WAREHOUSE_PUTAWAY_GET_BY_QA_RELEASE' },
  
  // Material Issue
  MATERIAL_ISSUE_CREATE: { cmd: 'WAREHOUSE_MATERIAL_ISSUE_CREATE' },
  MATERIAL_ISSUE_GET_BY_ID: { cmd: 'WAREHOUSE_MATERIAL_ISSUE_GET_BY_ID' },
  MATERIAL_ISSUE_LIST: { cmd: 'WAREHOUSE_MATERIAL_ISSUE_LIST' },
  MATERIAL_ISSUE_APPROVE: { cmd: 'WAREHOUSE_MATERIAL_ISSUE_APPROVE' },
  MATERIAL_ISSUE_PICK: { cmd: 'WAREHOUSE_MATERIAL_ISSUE_PICK' },
  MATERIAL_ISSUE_ISSUE: { cmd: 'WAREHOUSE_MATERIAL_ISSUE_ISSUE' },
  
  // Warehouse
  WAREHOUSE_CREATE: { cmd: 'WAREHOUSE_WAREHOUSE_CREATE' },
  WAREHOUSE_UPDATE: { cmd: 'WAREHOUSE_WAREHOUSE_UPDATE' },
  WAREHOUSE_GET_BY_ID: { cmd: 'WAREHOUSE_WAREHOUSE_GET_BY_ID' },
  WAREHOUSE_LIST: { cmd: 'WAREHOUSE_WAREHOUSE_LIST' },
  WAREHOUSE_DELETE: { cmd: 'WAREHOUSE_WAREHOUSE_DELETE' },
  
  // Storage Location
  LOCATION_CREATE: { cmd: 'WAREHOUSE_LOCATION_CREATE' },
  LOCATION_UPDATE: { cmd: 'WAREHOUSE_LOCATION_UPDATE' },
  LOCATION_GET_BY_ID: { cmd: 'WAREHOUSE_LOCATION_GET_BY_ID' },
  LOCATION_LIST: { cmd: 'WAREHOUSE_LOCATION_LIST' },
  LOCATION_DELETE: { cmd: 'WAREHOUSE_LOCATION_DELETE' },
  LOCATION_GET_BY_WAREHOUSE: { cmd: 'WAREHOUSE_LOCATION_GET_BY_WAREHOUSE' },
  
  // Cycle Count
  CYCLE_COUNT_CREATE: { cmd: 'WAREHOUSE_CYCLE_COUNT_CREATE' },
  CYCLE_COUNT_UPDATE: { cmd: 'WAREHOUSE_CYCLE_COUNT_UPDATE' },
  CYCLE_COUNT_GET_BY_ID: { cmd: 'WAREHOUSE_CYCLE_COUNT_GET_BY_ID' },
  CYCLE_COUNT_LIST: { cmd: 'WAREHOUSE_CYCLE_COUNT_LIST' },
  CYCLE_COUNT_START: { cmd: 'WAREHOUSE_CYCLE_COUNT_START' },
  CYCLE_COUNT_COMPLETE: { cmd: 'WAREHOUSE_CYCLE_COUNT_COMPLETE' },
  
  // Temperature Log
  TEMPERATURE_LOG_CREATE: { cmd: 'WAREHOUSE_TEMPERATURE_LOG_CREATE' },
  TEMPERATURE_LOG_GET_BY_ID: { cmd: 'WAREHOUSE_TEMPERATURE_LOG_GET_BY_ID' },
  TEMPERATURE_LOG_LIST: { cmd: 'WAREHOUSE_TEMPERATURE_LOG_LIST' },
  TEMPERATURE_LOG_GET_BY_REFERENCE: { cmd: 'WAREHOUSE_TEMPERATURE_LOG_GET_BY_REFERENCE' },
  
  // Label & Barcode
  LABEL_BARCODE_CREATE: { cmd: 'WAREHOUSE_LABEL_BARCODE_CREATE' },
  LABEL_BARCODE_UPDATE: { cmd: 'WAREHOUSE_LABEL_BARCODE_UPDATE' },
  LABEL_BARCODE_GET_BY_ID: { cmd: 'WAREHOUSE_LABEL_BARCODE_GET_BY_ID' },
  LABEL_BARCODE_LIST: { cmd: 'WAREHOUSE_LABEL_BARCODE_LIST' },
  LABEL_BARCODE_GET_BY_BARCODE: { cmd: 'WAREHOUSE_LABEL_BARCODE_GET_BY_BARCODE' },
  LABEL_BARCODE_GET_BY_REFERENCE: { cmd: 'WAREHOUSE_LABEL_BARCODE_GET_BY_REFERENCE' },
  LABEL_BARCODE_PRINT: { cmd: 'WAREHOUSE_LABEL_BARCODE_PRINT' },
};

export const MANUFACTURING_PATTERNS = {
  // Work Orders
  WORK_ORDER_CREATE: { cmd: 'MANUFACTURING_WORK_ORDER_CREATE' },
  WORK_ORDER_UPDATE: { cmd: 'MANUFACTURING_WORK_ORDER_UPDATE' },
  WORK_ORDER_GET_BY_ID: { cmd: 'MANUFACTURING_WORK_ORDER_GET_BY_ID' },
  WORK_ORDER_LIST: { cmd: 'MANUFACTURING_WORK_ORDER_LIST' },
  WORK_ORDER_DELETE: { cmd: 'MANUFACTURING_WORK_ORDER_DELETE' },
  
  // Batches
  BATCH_CREATE: { cmd: 'MANUFACTURING_BATCH_CREATE' },
  BATCH_UPDATE: { cmd: 'MANUFACTURING_BATCH_UPDATE' },
  BATCH_GET_BY_ID: { cmd: 'MANUFACTURING_BATCH_GET_BY_ID' },
  BATCH_LIST: { cmd: 'MANUFACTURING_BATCH_LIST' },
  BATCH_START: { cmd: 'MANUFACTURING_BATCH_START' },
  BATCH_COMPLETE: { cmd: 'MANUFACTURING_BATCH_COMPLETE' },
  BATCH_SUBMIT_TO_QC: { cmd: 'MANUFACTURING_BATCH_SUBMIT_TO_QC' },
  BATCH_RECEIVE_FINISHED_GOODS: { cmd: 'MANUFACTURING_BATCH_RECEIVE_FINISHED_GOODS' },
  BATCH_GET_BY_WORK_ORDER: { cmd: 'MANUFACTURING_BATCH_GET_BY_WORK_ORDER' },
  
  // Batch Steps
  BATCH_STEP_CREATE: { cmd: 'MANUFACTURING_BATCH_STEP_CREATE' },
  BATCH_STEP_UPDATE: { cmd: 'MANUFACTURING_BATCH_STEP_UPDATE' },
  BATCH_STEP_GET_BY_ID: { cmd: 'MANUFACTURING_BATCH_STEP_GET_BY_ID' },
  BATCH_STEP_LIST: { cmd: 'MANUFACTURING_BATCH_STEP_LIST' },
  BATCH_STEP_EXECUTE: { cmd: 'MANUFACTURING_BATCH_STEP_EXECUTE' },
  BATCH_STEP_GET_BY_BATCH: { cmd: 'MANUFACTURING_BATCH_STEP_GET_BY_BATCH' },
  
  // Material Consumption
  MATERIAL_CONSUMPTION_CREATE: { cmd: 'MANUFACTURING_MATERIAL_CONSUMPTION_CREATE' },
  MATERIAL_CONSUMPTION_GET_BY_ID: { cmd: 'MANUFACTURING_MATERIAL_CONSUMPTION_GET_BY_ID' },
  MATERIAL_CONSUMPTION_LIST: { cmd: 'MANUFACTURING_MATERIAL_CONSUMPTION_LIST' },
  MATERIAL_CONSUMPTION_GET_BY_BATCH: { cmd: 'MANUFACTURING_MATERIAL_CONSUMPTION_GET_BY_BATCH' },
};