import type { InventoryItem, PutawayTask, MovementRecord, CycleCount, WarehouseZone, WarehouseDashboardStats, FEFOItem, StockAdjustment, TemperatureAlert } from "@/types/warehouse"

// Mock Inventory Items Data
export const mockInventoryItems: InventoryItem[] = [
  {
    id: "1",
    itemCode: "INV-001",
    materialId: "1",
    materialName: "Paracetamol API",
    materialCode: "RM-001",
    batchNumber: "BATCH-001-2024",
    expiryDate: "2025-12-31",
    quantity: 45.5,
    unit: "kg",
    location: "A-01-01-01",
    zone: "A",
    rack: "01",
    shelf: "01",
    position: "01",
    status: "Available",
    temperature: 22.5,
    humidity: 55.2,
    lastUpdated: "2024-01-25T10:30:00Z",
    lastUpdatedBy: "8",
    lastUpdatedByName: "Mr. Muhammad Ali",
    remarks: "Good condition"
  },
  {
    id: "2",
    itemCode: "INV-002",
    materialId: "2",
    materialName: "Microcrystalline Cellulose",
    materialCode: "RM-002",
    batchNumber: "BATCH-002-2024",
    expiryDate: "2026-06-30",
    quantity: 23.8,
    unit: "kg",
    location: "A-01-01-02",
    zone: "A",
    rack: "01",
    shelf: "01",
    position: "02",
    status: "Available",
    temperature: 22.3,
    humidity: 54.8,
    lastUpdated: "2024-01-25T10:30:00Z",
    lastUpdatedBy: "8",
    lastUpdatedByName: "Mr. Muhammad Ali",
    remarks: "Good condition"
  },
  {
    id: "3",
    itemCode: "INV-003",
    materialId: "1",
    materialName: "Paracetamol Tablets",
    materialCode: "DRG-001",
    batchNumber: "BATCH-TAB-001-2024",
    expiryDate: "2025-03-15",
    quantity: 98500,
    unit: "tablets",
    location: "B-02-03-01",
    zone: "B",
    rack: "02",
    shelf: "03",
    position: "01",
    status: "Available",
    temperature: 20.8,
    humidity: 45.2,
    lastUpdated: "2024-01-24T15:45:00Z",
    lastUpdatedBy: "8",
    lastUpdatedByName: "Mr. Muhammad Ali",
    remarks: "Ready for distribution"
  },
  {
    id: "4",
    itemCode: "INV-004",
    materialId: "2",
    materialName: "Ibuprofen Tablets",
    materialCode: "DRG-002",
    batchNumber: "BATCH-TAB-002-2024",
    expiryDate: "2025-05-20",
    quantity: 74250,
    unit: "tablets",
    location: "B-02-03-02",
    zone: "B",
    rack: "02",
    shelf: "03",
    position: "02",
    status: "Quarantine",
    temperature: 21.2,
    humidity: 46.8,
    lastUpdated: "2024-01-24T16:00:00Z",
    lastUpdatedBy: "8",
    lastUpdatedByName: "Mr. Muhammad Ali",
    remarks: "Pending QC release"
  },
  {
    id: "5",
    itemCode: "INV-005",
    materialId: "3",
    materialName: "Sodium Starch Glycolate",
    materialCode: "RM-003",
    batchNumber: "BATCH-003-2024",
    expiryDate: "2025-08-15",
    quantity: 2.3,
    unit: "kg",
    location: "A-01-02-01",
    zone: "A",
    rack: "01",
    shelf: "02",
    position: "01",
    status: "Available",
    temperature: 22.1,
    humidity: 53.5,
    lastUpdated: "2024-01-25T09:15:00Z",
    lastUpdatedBy: "8",
    lastUpdatedByName: "Mr. Muhammad Ali",
    remarks: "Good condition"
  }
]

// Mock Putaway Tasks Data
export const mockPutawayTasks: PutawayTask[] = [
  {
    id: "1",
    taskNumber: "PUT-001",
    grnId: "1",
    grnNumber: "GRN-2024-001",
    materialId: "1",
    materialName: "Paracetamol API",
    materialCode: "RM-001",
    batchNumber: "BATCH-001-2024",
    quantity: 50.0,
    unit: "kg",
    status: "Completed",
    priority: "High",
    assignedTo: "8",
    assignedToName: "Mr. Muhammad Ali",
    assignedAt: "2024-01-25T08:00:00Z",
    startedAt: "2024-01-25T08:30:00Z",
    completedAt: "2024-01-25T10:30:00Z",
    sourceLocation: "Receiving Dock A",
    targetLocation: "A-01-01-01",
    targetZone: "A",
    targetRack: "01",
    targetShelf: "01",
    targetPosition: "01",
    temperatureCompliance: true,
    createdBy: "3",
    createdByName: "Mr. Ali Hassan",
    createdAt: "2024-01-25T07:45:00Z",
    remarks: "Putaway completed successfully"
  },
  {
    id: "2",
    taskNumber: "PUT-002",
    grnId: "2",
    grnNumber: "GRN-2024-002",
    materialId: "2",
    materialName: "Microcrystalline Cellulose",
    materialCode: "RM-002",
    batchNumber: "BATCH-002-2024",
    quantity: 25.0,
    unit: "kg",
    status: "Completed",
    priority: "High",
    assignedTo: "8",
    assignedToName: "Mr. Muhammad Ali",
    assignedAt: "2024-01-25T08:00:00Z",
    startedAt: "2024-01-25T08:30:00Z",
    completedAt: "2024-01-25T10:30:00Z",
    sourceLocation: "Receiving Dock A",
    targetLocation: "A-01-01-02",
    targetZone: "A",
    targetRack: "01",
    targetShelf: "01",
    targetPosition: "02",
    temperatureCompliance: true,
    createdBy: "3",
    createdByName: "Mr. Ali Hassan",
    createdAt: "2024-01-25T07:45:00Z",
    remarks: "Putaway completed successfully"
  },
  {
    id: "3",
    taskNumber: "PUT-003",
    grnId: "3",
    grnNumber: "GRN-2024-003",
    materialId: "1",
    materialName: "Paracetamol Tablets",
    materialCode: "DRG-001",
    batchNumber: "BATCH-TAB-001-2024",
    quantity: 100000,
    unit: "tablets",
    status: "In Progress",
    priority: "Normal",
    assignedTo: "8",
    assignedToName: "Mr. Muhammad Ali",
    assignedAt: "2024-01-24T14:00:00Z",
    startedAt: "2024-01-24T15:00:00Z",
    sourceLocation: "Production Area",
    targetLocation: "B-02-03-01",
    targetZone: "B",
    targetRack: "02",
    targetShelf: "03",
    targetPosition: "01",
    temperatureCompliance: true,
    createdBy: "6",
    createdByName: "Mr. Hassan Ali",
    createdAt: "2024-01-24T13:30:00Z",
    remarks: "Putaway in progress"
  },
  {
    id: "4",
    taskNumber: "PUT-004",
    grnId: "4",
    grnNumber: "GRN-2024-004",
    materialId: "2",
    materialName: "Ibuprofen Tablets",
    materialCode: "DRG-002",
    batchNumber: "BATCH-TAB-002-2024",
    quantity: 75000,
    unit: "tablets",
    status: "Pending",
    priority: "Normal",
    assignedTo: "8",
    assignedToName: "Mr. Muhammad Ali",
    assignedAt: "2024-01-24T16:00:00Z",
    sourceLocation: "Production Area",
    targetLocation: "B-02-03-02",
    targetZone: "B",
    targetRack: "02",
    targetShelf: "03",
    targetPosition: "02",
    temperatureCompliance: true,
    createdBy: "6",
    createdByName: "Mr. Hassan Ali",
    createdAt: "2024-01-24T15:45:00Z",
    remarks: "Awaiting QA release"
  }
]

// Mock Movement Records Data
export const mockMovementRecords: MovementRecord[] = [
  {
    id: "1",
    movementNumber: "MOV-001",
    movementType: "Receipt",
    materialId: "1",
    materialName: "Paracetamol API",
    materialCode: "RM-001",
    batchNumber: "BATCH-001-2024",
    quantity: 50.0,
    unit: "kg",
    fromLocation: "Receiving Dock A",
    toLocation: "A-01-01-01",
    fromZone: "Receiving",
    toZone: "A",
    fromRack: "DOCK-01",
    toRack: "01",
    fromShelf: "01",
    toShelf: "01",
    fromPosition: "01",
    toPosition: "01",
    reason: "Material receipt from supplier",
    performedBy: "8",
    performedByName: "Mr. Muhammad Ali",
    performedAt: "2024-01-25T10:30:00Z",
    referenceDocument: "GRN",
    referenceNumber: "GRN-2024-001",
    remarks: "Material received and put away"
  },
  {
    id: "2",
    movementNumber: "MOV-002",
    movementType: "Consumption",
    materialId: "1",
    materialName: "Paracetamol API",
    materialCode: "RM-001",
    batchNumber: "BATCH-001-2024",
    quantity: 4.5,
    unit: "kg",
    fromLocation: "A-01-01-01",
    toLocation: "Production Area",
    fromZone: "A",
    toZone: "Production",
    fromRack: "01",
    toRack: "PROD-01",
    fromShelf: "01",
    toShelf: "01",
    fromPosition: "01",
    toPosition: "01",
    reason: "Material consumption for batch production",
    performedBy: "6",
    performedByName: "Mr. Hassan Ali",
    performedAt: "2024-01-25T14:00:00Z",
    referenceDocument: "Work Order",
    referenceNumber: "WO-001",
    remarks: "Material consumed for batch BATCH-001-2024"
  },
  {
    id: "3",
    movementNumber: "MOV-003",
    movementType: "Transfer",
    materialId: "1",
    materialName: "Paracetamol Tablets",
    materialCode: "DRG-001",
    batchNumber: "BATCH-TAB-001-2024",
    quantity: 100000,
    unit: "tablets",
    fromLocation: "Production Area",
    toLocation: "B-02-03-01",
    fromZone: "Production",
    toZone: "B",
    fromRack: "PROD-01",
    toRack: "02",
    fromShelf: "01",
    toShelf: "03",
    fromPosition: "01",
    toPosition: "01",
    reason: "Finished goods transfer to warehouse",
    performedBy: "8",
    performedByName: "Mr. Muhammad Ali",
    performedAt: "2024-01-24T15:45:00Z",
    referenceDocument: "Batch Record",
    referenceNumber: "BATCH-001-2024",
    remarks: "Finished goods transferred to warehouse"
  }
]

// Mock Cycle Counts Data
export const mockCycleCounts: CycleCount[] = [
  {
    id: "1",
    countNumber: "CC-001",
    countType: "ABC Count",
    status: "Completed",
    zone: "A",
    assignedTo: "8",
    assignedToName: "Mr. Muhammad Ali",
    scheduledDate: "2024-01-20T09:00:00Z",
    startedAt: "2024-01-20T09:15:00Z",
    completedAt: "2024-01-20T11:30:00Z",
    items: [
      {
        id: "1",
        materialId: "1",
        materialName: "Paracetamol API",
        materialCode: "RM-001",
        batchNumber: "BATCH-001-2024",
        systemQuantity: 50.0,
        countedQuantity: 49.8,
        variance: -0.2,
        variancePercentage: -0.4,
        status: "Verified",
        countedBy: "8",
        countedByName: "Mr. Muhammad Ali",
        countedAt: "2024-01-20T09:30:00Z",
        verifiedBy: "9",
        verifiedByName: "Ms. Fatima Hassan",
        verifiedAt: "2024-01-20T10:00:00Z",
        remarks: "Minor variance within acceptable limits"
      }
    ],
    totalItems: 5,
    countedItems: 5,
    varianceItems: 1,
    createdBy: "9",
    createdByName: "Ms. Fatima Hassan",
    createdAt: "2024-01-19T16:00:00Z",
    remarks: "Cycle count completed successfully"
  },
  {
    id: "2",
    countNumber: "CC-002",
    countType: "Full Count",
    status: "In Progress",
    zone: "B",
    assignedTo: "8",
    assignedToName: "Mr. Muhammad Ali",
    scheduledDate: "2024-01-26T09:00:00Z",
    startedAt: "2024-01-26T09:00:00Z",
    items: [
      {
        id: "2",
        materialId: "1",
        materialName: "Paracetamol Tablets",
        materialCode: "DRG-001",
        batchNumber: "BATCH-TAB-001-2024",
        systemQuantity: 100000,
        countedQuantity: 98500,
        variance: -1500,
        variancePercentage: -1.5,
        status: "Counted",
        countedBy: "8",
        countedByName: "Mr. Muhammad Ali",
        countedAt: "2024-01-26T09:30:00Z",
        remarks: "Variance detected - needs investigation"
      }
    ],
    totalItems: 3,
    countedItems: 1,
    varianceItems: 1,
    createdBy: "9",
    createdByName: "Ms. Fatima Hassan",
    createdAt: "2024-01-25T16:00:00Z",
    remarks: "Cycle count in progress"
  }
]

// Mock Warehouse Zones Data
export const mockWarehouseZones: WarehouseZone[] = [
  {
    id: "1",
    zoneCode: "A",
    zoneName: "Raw Materials Zone",
    temperature: 22.0,
    humidity: 55.0,
    capacity: 1000,
    unit: "kg",
    materialTypes: ["API", "Excipients", "Raw Materials"],
    isActive: true,
    locations: [
      {
        id: "1",
        locationCode: "A-01-01-01",
        zone: "A",
        rack: "01",
        shelf: "01",
        position: "01",
        capacity: 100,
        unit: "kg",
        temperature: 22.5,
        humidity: 55.2,
        status: "Occupied",
        materialType: ["API"],
        lastUpdated: "2024-01-25T10:30:00Z",
        lastUpdatedBy: "8",
        lastUpdatedByName: "Mr. Muhammad Ali",
        remarks: "Paracetamol API storage"
      },
      {
        id: "2",
        locationCode: "A-01-01-02",
        zone: "A",
        rack: "01",
        shelf: "01",
        position: "02",
        capacity: 100,
        unit: "kg",
        temperature: 22.3,
        humidity: 54.8,
        status: "Occupied",
        materialType: ["Excipients"],
        lastUpdated: "2024-01-25T10:30:00Z",
        lastUpdatedBy: "8",
        lastUpdatedByName: "Mr. Muhammad Ali",
        remarks: "Microcrystalline Cellulose storage"
      }
    ]
  },
  {
    id: "2",
    zoneCode: "B",
    zoneName: "Finished Goods Zone",
    temperature: 20.0,
    humidity: 45.0,
    capacity: 500000,
    unit: "tablets",
    materialTypes: ["Tablets", "Capsules", "Finished Products"],
    isActive: true,
    locations: [
      {
        id: "3",
        locationCode: "B-02-03-01",
        zone: "B",
        rack: "02",
        shelf: "03",
        position: "01",
        capacity: 100000,
        unit: "tablets",
        temperature: 20.8,
        humidity: 45.2,
        status: "Occupied",
        materialType: ["Tablets"],
        lastUpdated: "2024-01-24T15:45:00Z",
        lastUpdatedBy: "8",
        lastUpdatedByName: "Mr. Muhammad Ali",
        remarks: "Paracetamol Tablets storage"
      },
      {
        id: "4",
        locationCode: "B-02-03-02",
        zone: "B",
        rack: "02",
        shelf: "03",
        position: "02",
        capacity: 100000,
        unit: "tablets",
        temperature: 21.2,
        humidity: 46.8,
        status: "Occupied",
        materialType: ["Tablets"],
        lastUpdated: "2024-01-24T16:00:00Z",
        lastUpdatedBy: "8",
        lastUpdatedByName: "Mr. Muhammad Ali",
        remarks: "Ibuprofen Tablets storage"
      }
    ]
  }
]

// Mock FEFO Items Data
export const mockFEFOItems: FEFOItem[] = [
  {
    id: "1",
    materialId: "1",
    materialName: "Paracetamol Tablets",
    materialCode: "DRG-001",
    batchNumber: "BATCH-TAB-001-2024",
    expiryDate: "2025-03-15",
    quantity: 98500,
    unit: "tablets",
    location: "B-02-03-01",
    daysToExpiry: 49,
    priority: "High",
    status: "Available"
  },
  {
    id: "2",
    materialId: "2",
    materialName: "Ibuprofen Tablets",
    materialCode: "DRG-002",
    batchNumber: "BATCH-TAB-002-2024",
    expiryDate: "2025-05-20",
    quantity: 74250,
    unit: "tablets",
    location: "B-02-03-02",
    daysToExpiry: 115,
    priority: "Medium",
    status: "Quarantine"
  },
  {
    id: "3",
    materialId: "1",
    materialName: "Paracetamol API",
    materialCode: "RM-001",
    batchNumber: "BATCH-001-2024",
    expiryDate: "2025-12-31",
    quantity: 45.5,
    unit: "kg",
    location: "A-01-01-01",
    daysToExpiry: 340,
    priority: "Low",
    status: "Available"
  }
]

// Mock Stock Adjustments Data
export const mockStockAdjustments: StockAdjustment[] = [
  {
    id: "1",
    adjustmentNumber: "ADJ-001",
    materialId: "1",
    materialName: "Paracetamol API",
    materialCode: "RM-001",
    batchNumber: "BATCH-001-2024",
    location: "A-01-01-01",
    systemQuantity: 50.0,
    actualQuantity: 49.8,
    adjustmentQuantity: -0.2,
    reason: "Cycle count variance",
    status: "Approved",
    requestedBy: "8",
    requestedByName: "Mr. Muhammad Ali",
    requestedAt: "2024-01-20T11:30:00Z",
    approvedBy: "9",
    approvedByName: "Ms. Fatima Hassan",
    approvedAt: "2024-01-20T12:00:00Z",
    remarks: "Minor variance within acceptable limits"
  }
]

// Mock Temperature Alerts Data
export const mockTemperatureAlerts: TemperatureAlert[] = [
  {
    id: "1",
    alertNumber: "TEMP-001",
    location: "A-01-01-01",
    zone: "A",
    materialId: "1",
    materialName: "Paracetamol API",
    batchNumber: "BATCH-001-2024",
    currentTemperature: 25.5,
    minTemperature: 20.0,
    maxTemperature: 25.0,
    severity: "Medium",
    status: "Acknowledged",
    triggeredAt: "2024-01-25T14:30:00Z",
    acknowledgedBy: "8",
    acknowledgedByName: "Mr. Muhammad Ali",
    acknowledgedAt: "2024-01-25T14:45:00Z",
    remarks: "Temperature slightly above range, monitoring"
  }
]

// Mock Dashboard Statistics
export const mockWarehouseDashboardStats: WarehouseDashboardStats = {
  totalItems: 1250,
  availableItems: 1100,
  quarantineItems: 50,
  holdItems: 75,
  rejectedItems: 25,
  totalLocations: 500,
  occupiedLocations: 350,
  availableLocations: 150,
  pendingPutaway: 5,
  inProgressPutaway: 2,
  completedPutaway: 45,
  totalMovements: 125,
  pendingCycleCounts: 3,
  activeAlerts: 2,
  averagePutawayTime: 2.5,
  inventoryAccuracy: 98.5
}
